<!DOCTYPE html>

	<head>
        <meta charset="UTF-8">
        <title>La Cuisine Du Monde</title>
        <link rel="stylesheet" href="./Connexion/Connexion.css">
        <script src="http://code.jquery.com/jquery-latest.js"></script>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

        <!-- <script src="header.js"></script> -->
    </head>
	
	
	<body>
	  <form action="connexion.php?action=entrer" method="post">	      
	  <div class = "Formulaire">
         <p id="ecriture">Se connecter :</p>
         <label for="pseudo"class="pseudo1" >Log-in :</label>
         <input type="text" name="pseudo" class="pseudo2" />
         <br />
         <label for="pass" class="pass1">Votre mot de passe :</label>
         <input type="password" name="pass" class="pass2" />
           <br />
         <input type="submit" value="Connexion" name="boutonCo" id="boutonco"/>
      </div>
    <div class = "connexioninscription">
        <input type="button" value="Inscription"  name ="boutonInscript" class ="boutonInscription" OnClick=".'"window.location='.'"./inscription.php?action=showForm//">/>
        <input type="button" value="Mot de passe oublié" name ="boutonMdpOublie" class ="boutonMdpoub"/>
    </div>
    <div class = "maiil">
        <p id ="mail">En cas de problème de connexion, veuillez contacter le webmaster sur l’adresse suivante : 
            <br />
        alex@webmaster.com
        </p>
    </div>
        </form>
    </body>