<!DOCTYPE html>
<html>
	
	<head>
		<title> L'une de vos recettes préférées </title>
		<link rel="stylesheet" href="Recette/RecetteNouveau.css" />
		<meta charset = "utf-8">
		<link rel="stylesheet" href = "bootstrap.css">
		<style type = "text/css">
		nav{
		background-color : #023B5C;
		}
		</style>
	</head>
	<body>
	    
	    
        <div id ="page">

        <header id = "rass">
            <nav id ="nav" class="navbar navbar-inverse navbar-fixed-top">
                <ul class = "nav navbar-nav">
                    <li> <a id="Nomsite">La cuisine du Monde</a></li>
                    </ul>
                    <ul class = "nav navbar-nav">
                    <form class="nav navbar-form" >
                    <input type="text" class="input-sm" placeholder='Entrez votre recherche'>
                    <button type ="susbmit" class ="btn btn-primary btn-sm">Rechercher</button>
                    </form>
                    </ul>
                <ul class ="nav navbar-bav navbar-right">
                    <li id ="notif"><a href="Notification.html" target="_blank"> Notifications</a></li>
                    <li id="connexion"><a href="Connexion.html" target="_blank">Connexion</a></li>
                </ul>
            </nav>
        </header>

        <div id = "ContenuPage">
                <p class = "entete" >
                <h1 id ="nomRec"> <?php echo $Recette->getTitre();?></h1>

                <li id = "noteRec"> Note : <?php echo $Recette->getNote();echo 'MANQUE IMPLEMENTATION';?> </li> 
                <li id = "typeRec">Type <?php echo $Recette->getType();echo 'MANQUE IMPLEMENTATION';?></li>
                </br>
                <li id="nbPrsRec">Nombre personnes : <?php echo $Recette->getNb_De_Personne();?>     </li>    
                <li id="tempsRec">Temps préparation :<?php echo $Recette->getTemps();?></li>
                </p>
                <div  id = "contenaire">
                <p class="ImageRecette">
                    <img src="Recette/ImageRecette.png" alt="ImageRecette">
                    
                    <!--  

                    //INGREDIENTS, IL N'EXISTE PAS LA REQUETE
                    <?php echo $Recette->getIngredients(); echo 'MANQUE IMPLEMENTATION';?>

                    -->
                    
                    
                    Ingredients :</br>  - 500 g de farine (farine de gruau de préférence, sinon de la T45)</br>  - 80 g de sucre en poudre </br> - 8 g de sel</br>  - 25 g de levure fraîche </br> - 2 oeufs </br> - 180 ml de lait entier à température ambiante </br> - 100 g de beurre pommade
                </p>


                <p id = "pub">Publié par : <?php echo $Recette->getAuteur();?></p>
                <div id="decription">
                <p class = "descript">Description :</br></br><?php echo $Recette->getDescription();?>
                    </div>
                    </div>
            </div>

		
	</body>
	