<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>La Cuisine Du Monde</title>
        <link rel="stylesheet" href="autre-utilisateur/View/autreUtilisateur.css">
    </head>
    
     <body>
        
        <div id="partieHaute" >
            <div id = "photoutil">
                <?php echo '<img id = "toto" src="Images/User/'.$id.'.jpg">' ?>
            </div>
            <div id ="infosProfil">
                  <li class = "nomUtil"> <?php echo $_GET['auteur'] ?> </li>
                <li class = "mailUtil"> <?php echo $mailUtilisateur?> </li>
            </div>
            <div id ="nombreRec">
                Nombre de recettes proposées : <?php echo $nombreRec ?>
            </div>
        </div>
        <div id = "partieBasse">
             <form>
                    <input id = "suivre"
                               type="button"
                           value="Suivre">
                </form>
            <div class = "recprop">
                Recettes proposées : 
            </div>
             <!--<div class="Recette-petit center" >
           <a href="Recette/RecetteNouveau.html">
               <img class="image-petit" src="./Profil-recettes/View/image-petit.jpg">
           </a>
            <h3 class="title">Brioche Tressée</h3>   
            <h4 class="Note">Note 4.5</h4>
            <h4 class="Temps">Temps de preparation 15 min</h4>
            <br/>
            <h4 class="Ingredients">
                Ingredients : <br/>
            * 500 g de farine (farine de gruau * de préférence, sinon de la T45)<br/>
            * 80 g de sucre en poudre<br/>
            * 8 g de sel ...<br/></h4>
            <h4 class="description">Pour cette recette, je voulais une brioche parfaite à manger juste comme ça, sans forcément mettre de la confiture ou de la pâte à tartiner dessus, même si cela reste possible.
            Et je suis super contente du résultat ! ...</h4>
       
            </div>-->
            <?php 
            
                foreach($Recette as $value ){
            echo'
                 <div class="Recette-petit center" >
           <a href="recette.php?numRecette=1&action=afficherCommentaires">
               <img class="image-petit" src="./monEspacePerso/View/image-petit.jpg">
           </a>
            <h3 class="title">'.$value['Titre'].'</h3>   
            <h4 class="Note">Note 4.5</h4>
            <h4 class="Temps">'.$value['Temps'].'</h4>
            <br/>
                 </h4>
            <h4 class="description">';
                    if(str_word_count($value['Description']) > 100){
                    $arr = explode(' ',trim($value['Description']));
                    for($i = 0 ; $i < 100 ; $i++){
                        echo $arr[$i]." ";
                    }
                    echo '...';
                }else{
                 echo $value['Description'];  
                 }
            echo '</h4>
       
            </div>';
            }
            
            
            ?>
         
         </div>
        
        
        
        
        
            </body>