<!DOCTYPE html>

	<head>
        <meta charset="UTF-8">
        <title>La Cuisine Du Monde</title>
        <link rel="stylesheet" href="Commentaire.css">
        <script src="http://code.jquery.com/jquery-latest.js"></script>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

        <!-- <script src="header.js"></script> -->
    </head>
	
	
	<body>
	  <form>
	  <div class = "Formulaire">
         
          <div class ="ecriture">
                <!-- inserer l'image pour l'instant on va mettre un cadre normal 
                    <img src=" ">-->
              <div class = "image">
                  photo utilisateur
              </div>
              <div class="commentairee">
                  <textarea rows ="5" cols ="95" class="commentaire"></textarea>
              </div>
              <div id= "boutoncomm">
                    <input id = "comm"
                   type="submit"
               value="Commenter">
             </div>
          </div>
          
          
          <div class="dejaecri">
            <div id ="exemplecom">
                <div id="nomuti">
                    Nom utilisateur
                </div>
                <div id="photocom">
                    <!-- inserer l'image pour l'instant on va mettre un cadre normal 
                    <img src=" ">-->
                    photo utilisateur
                </div>
                <div id="comecri">
                    Commentaire de la personne
                </div>
              </div>
              
          </div>
          
        </div>
            </form>
        </body>