<!DOCTYPE html>

	<head>
        <meta charset="UTF-8">
        <title>La Cuisine Du Monde</title>
        <link rel="stylesheet" href="./Inscription/PageInscription.css">
        <script src="http://code.jquery.com/jquery-latest.js"></script>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

        <!-- <script src="header.js"></script> -->
    </head>
	
	
	<body>

	   <form action="inscription.php?action=submit" method="post">
	      
	   <div class = "Formulaire">

            <div id = "genre">
                <p id="civilite"> * Civilité :
                    <input type="radio" name="gen" value="M" ><label for="Mr">Mr</label>
                    <input type="radio" name="gen" value="F" ><label for="Mme">Mme</label>
                </p>
            </div>

           <div id ="pseudo">
                <label for="pseudo">* Votre pseudo :</label>
                <input type="text" name="pseudo" placeholder="Ex : Zozor" />
           </div>


            <div id = "pass">
               <label for="pass">* Votre mot de passe :</label>
               <input type="password" name="pass" id="passp" />
           </div>

           <div id="confirmpass">
               <label for="confirmpass">* Confirmez votre mot de passe :</label>
               <input type="password" name="confimpass" id="confirpass" />
           </div>

           <div id ="admail">
                   <label for="mail">Votre adresse mail :</label>
                   <input type="email" name="mail" id="mail"  placeholder="Ex : Zozor90@hotmail.fr"  />
            </div>

            <div id ="commentaire">
                <p>Commentaires : </p>
                <textarea rows ="5" cols ="95"></textarea>
            </div>

            <div id ="confidentialite">
                <input  type="checkbox" name="pfm" value="dos"><U><I> * Confidentialité des données utilisteur:</I></U></br>
                Les informations personnelles que nous collections sont destinées a mieux répondre à vos demandes et attentes et traiter vos recherches.
                Vous disposez à tout moment d’un droit d’accès, de modification et de suppression de vos informations personnelles que vous pouvez exercer via la page “mon espace personnel” de ce site.
            </div>

            <div id ="finpage">

                <div id ="champsrequis">
                    * Champs requis
                </div>

            <div id= "boutonfin">
                    <input id = "inscription"
                   type="submit"
               value="S'inscrire">
             </div>

             </div>

	       
	       
	       
	       
	   </form>
		
	  </body>