<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>La Cuisine Du Monde</title>
        <link rel="stylesheet" href="Recherche.css">
        <script src="http://code.jquery.com/jquery-latest.js"></script>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

        <!-- <script src="header.js"></script> -->
    </head>
    <body>
        
        <div id ="contenuPage">
            <div id ="RechercheUser">
                <div id=Vide>
                <img class = "image" src="profil-vide.jpg">  
            </div>
                
            <div id="infos">
                  <li class = "nomUtil"> User : </li>
                <li class = "mailUtil"> Mail :  </li>
            </div>
            </div>
            <div id ="RechercheRecette">
                
            <div id="rec">
                  <li class = "Auteur"> Author : </li>
                <li class = "Titre"> MailUser :  </li>
                <li class = "TempsPreparation"> Temps Préparation :  </li>
                <li class = "Description"> Description :  </li>
            </div>
        </div>
        </div>
        
    </body>